spring:
  datasource:
    read:
      url: ${JDBC_DATASOURCE_URL}
      username: ${JDBC_PRIMARY_RW_USERNAME}
      password: ${JDBC_PRIMARY_RW_PWD}
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        poolName: slavePool
        maximumPoolSize: 50
        minimumIdle: 5
        idleTimeout: 60000
        connectionTimeout: 30000
        maxLifetime: 1500000
        auto-commit: true
        connectionTestQuery: SELECT 1 FROM DUAL
        validationTimeout: 5000
        leakDetectionThreshold: 2000
        initializationFailTimeout: 1

    write:
      url: ${JDBC_DATASOURCE_URL}
      username: ${JDBC_PRIMARY_RW_USERNAME}
      password: ${JDBC_PRIMARY_RW_PWD}
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        poolName: masterPool
        maximumPoolSize: 50
        minimumIdle: 5
        idleTimeout: 60000
        connectionTimeout: 30000
        maxLifetime: 1500000
        auto-commit: true
        connectionTestQuery: SELECT 1 FROM DUAL
        validationTimeout: 5000
        leakDetectionThreshold: 2000
        initializationFailTimeout: 1

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: false
